### ISSUE TITLE
Recordset Endpoint 

### ISSUE THREAD

**Issue by kevinlove** [iDigBio/idigbio-search-api#24]
Getting errors when running this code

```r
library(jsonlite)
rsEP <- "http://search.idigbio.org/v2/search/recordsets?limit=1"
rsDF <- fromJSON(rsEP)
```

Any ideas @mjcollin ?

**Comment by sckott** [comment]
works fine for me - what errors are you getting?

**Comment by godfoder** [comment]
Kevin and I were testing this out on his computer and getting an error. I think the problem we were having was not explicitly with the code aboce, but with using the View function in RStudio on the dataframe created.

```
library(jsonlite)
rsEP <- "http://search.idigbio.org/v2/search/recordsets?limit=2000"
rsDF <- fromJSON(rsEP)
```

Works fine, and the dataframe can be used subsequently to perform the needed operations.

Using View(rsDF) produces the error: 'names' attribute [1] must be the same length as the vector [0]. which is the error we were getting on his computer as well.

I think that at some point this worked, and that he had the dataframe pinned open in RStudio, so that it was generating an error message every time he tried to refresh that data.

**Comment by kevinlove** [comment]
I guess I should have added a little background to the ticket @sckott , I was just using it as a placeholder for follow up with the team:

I've been using jsonlite to parse JSON responses from the recordset endpoint without issue. I noticed yesterday that jsonlite(1.1) is now throwing the error:

> Error in names(cols) <- paste(names(framecol)[[1]], names(cols), sep = ".") : 
  'names' attribute [1] must be the same length as the vector [0] 

We were trying to work through the root cause of this and determine if jsonlite is choking on the API response due to changes in the index or if it just has a bug. 

Can you confirm your version of the jsonlite package? I don't seem to be able to reproduce it with 0.9.13

**Comment by sckott** [comment]
@kevinlove I'm on version `1.2` - i wouldn't expect there to be a problem with `jsonlite` itself unless there was a server error or something

**Comment by kevinlove** [comment]
Thanks, we will chalk this one up to having a bad day. Thanks for the extra info everyone.
