### ISSUE TITLE
Error handling in the API is sub-par at best.

### ISSUE THREAD

**Issue by godfoder** [iDigBio/idigbio-search-api#4]
Curious if I'm missing something, but in my exploration of the APIs so far it seems that there are no error messages describing problems in a query. e..g. 

https://beta-search.idigbio.org/v2/search/records?rq={"purple":"acer"}

Where I assume `purple` is not a valid parameter. This gives 

{

    itemCount: 0,
    lastModified: "1970-01-01T00:00:00.000Z",
    items: [ ],
    attribution: [ ]

}

Which is right in that there's no results, but would be super helpful if a message was given indicating that `purple` is not a valid parameter, e.g. 

In another example, 

https://beta-search.idigbio.org/v2/search/records?limit=adfasdf

where a character string is passed instead of a number - that parameter is silently dropped I assume (using the default of 10). 

In the `limit` parameter case, that behavior seems consistent with other APIs (e.g., GBIF). But in the first example, I'd think a message would be returned indicating that there was an error in parsing, and X was expected. 

Thanks!
Scott Chamberlain

**Comment by sckott** [comment]
thanks for posting here :smile:

**Comment by danstoner** [comment]
Please consider fixing all cases where a poorly supplied request (e.g. an error in query format) returns "all of iDigBio" (all records).  While learning an API there is a natural progression from "getting nothing back" to "getting something back" to "getting back exactly what I want".

I have stumbled on a few occasions because my "bad" query gave me back an answer (e.g. pages of JSON scrolling on my screen) making me think I was still progressing towards "getting back exactly what I want" but then having to backtrack. Bad query should really result in "getting nothing back" to aid in learning the API.

**Comment by godfoder** [comment]
Basic parse errors should be fixed now, and return somewhat informative error messages. This should include all categories of numeric parsing returning NaN, and JSON parsing throwing an exception.

Semantic parsing will come later, as it takes a bit more time.

**Comment by sckott** [comment]
great, thanks!
